name: Publish package
on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test:ci

      - name: Run typecheck
        run: yarn typecheck

      - name: Run linter
        run: yarn lint:ci

      - name: Semantic Release
        run: yarn run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
